# Generated by Django 5.1.6 on 2026-10-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_pushsubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pushsubscription",
            name="endpoint",
            field=models.URLField(max_length=500),
        ),
    ]
