# Generated by Django 5.1.6 on 2026-03-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_direct',
            field=models.BooleanField(default=False),
        ),
    ]
