# Generated by Django 6.0.2 on 2026-03-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_roominvitation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomparticipant',
            options={'ordering': ['-is_pinned', 'created_at']},
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
