# Generated by Django 5.1.6 on 2026-10-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0005_room_public_channel_and_bans"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomban",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
